config:
  bind: 0.0.0.0:25565
  lite:
    enabled: true
    routes:
      - host: 'example.com'
        backend: host1:25565
        fallback:
          motd: |
            §c遠端伺服器離線
            §e請連絡管理員
          version:
            name: '§c稍後再試！'
            protocol: -1

      - host: '*'
        backend: host1:25565
        fallback:
          motd: |
            §c遠端伺服器離線
            §e請連絡管理員
          version:
            name: '§c稍後再試！'
            protocol: -1
